---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Define nginx user
- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

#Setup/install nginx tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'  

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes

# Setup/install php-fpm 7.0 tasks.
- include: setup-php7.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure php-fpm is started and enabled to start at boot.
  service: name=php70-php-fpm state=started enabled=yes

#Setup/install Composer
- include: setup-composer.yml

# Create magento2 CE project with composer
- include: setup-magento2-composer.yml

# Vhost configuration.
- include: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  notify:
    - reload nginx

# Setup/install MariaDB tasks.
- include: setup-mariadb.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure mariadb is started and enabled to start at boot.
  service: name="{{ mariadb_service }}" state=started enabled=yes

# Setup/install Redis tasks.
- include: setup-redis.yml
  when: ansible_os_family == 'RedHat'

# Install Magento 2 from CLI
- include: install-magento2.yml
  notify:
    - restart nginx